### ISSUE TITLE
Ask about adding TypeScript declarations

### ISSUE THREAD

**Issue by IgorShcherba** [ChetSocio/easy-magnify#1]
Hello  @ChetSocio, 

Are there any plans to introduce TS type declarations for this package? Alternatively, are the types from `react-image-magnify` compatible with this package?

**Comment by ChetSocio** [comment]
I have not touched this project since last commit. I was trying to create this as a component for ui library that was to be used in my ecommerce startup. I will mention you another similar project i was working closely with within 12 hours

**Comment by ChetSocio** [comment]
Maybe i will just create this as a component for my ui library in future. Will not revive this project.

**Comment by ChetSocio** [comment]
okay work is on for this project. Will add tons of features and typescript declarations for this. stay tuned

**Comment by nikasepiskveradze** [comment]
Any news about this?

**Comment by ChetSocio** [comment]
> Any news about this?

Hey can you tell me what kind of updates is necessary for this package (except changing class components to functional components and adding typescript declarations as I am working on them) ?? Is there any incompatibility issues with react or something that is unnoticed by me?

**Comment by nikasepiskveradze** [comment]
Yeah my main interest is type declaration, I don't want to be impatient but will be update soon?

**Comment by ChetSocio** [comment]
Yes work is on but this will be breaking change, whole library is being rewritten into functional components and typescript support by default. Will take few days (2-3 more). Will be upgraded, have better support for react and performance benefits. Remember:L APIs will be changed too.

**Comment by ChetSocio** [comment]
I am updating code frequently and am testing code on my side. Npm package will be updated after i update and publish docs at easy-magnify.batchnepal.com

 I am working on integrating webpack. Maybe take few days from today

**Comment by ChetSocio** [comment]
I am closing this issue as package has been upgraded to support typescript and react 18. I hope this solves the issue. 
If you have any issues while using this package, the please open new one
