### ISSUE TITLE
easy-magnify-zoom property

### ISSUE THREAD

**Issue by GiannouliDimitra** [ChetSocio/easy-magnify#6]
Hello all,
I use the package and I want to use the zoom property in the EasyZoomOnMove component.
Is there any property for the zoom scale?

Thank you.

**Comment by ChetSocio** [comment]
There is no current plan to introduce zoom property on EasyZoomOnMove component. Maybe will introduce in future. The current zoom is quiet balanced for most use cases. In upcoming update , I will be fixing image sizing issues
